name: veryreal_common
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  dio: ^5.0.2
  talker_dio_logger: ^4.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.18
  sprintf: ^7.0.0
  uuid: ^4.4.0
  flutter_bugly: ^0.4.4
  path_provider: ^2.0.13
  android_path_provider: ^0.3.0
  image_picker: ^1.1.2
  flutter_easyloading: ^3.0.5
  rxdart: ^0.27.7
  permission_handler: ^11.3.1
  # wechat_camera_picker: 
  extended_image: ^8.2.1
  image_gallery_saver: ^2.0.3
  open_filex: ^4.3.2
  lottie: ^3.1.2
  r_scan: ^0.1.6+1
  image_cropper: ^7.0.5
  package_info_plus: ^8.0.0
  crypto: ^3.0.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.10
  common_utils: ^2.1.0
  uri_to_file: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_image_compress: ^2.3.0
  font_awesome_flutter: ^10.4.0
  just_audio: ^0.9.36
  vibration: ^1.7.6
  local_auth: ^2.1.6
  local_auth_android: ^1.0.21
  local_auth_darwin: ^1.1.1
  device_info_plus: ^10.1.0
  visibility_detector: ^0.4.0+2
  record: ^5.1.2
  mime: ^1.0.4
  chewie: ^1.4.0
  video_player: ^2.6.0
  flutter_cache_manager: ^3.3.1
  syncfusion_flutter_core: ^26.1.39
  syncfusion_flutter_sliders: ^26.1.39
  ffmpeg_kit_flutter_full_gpl: 6.0.3
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.0
  google_api_availability: ^5.0.0
  flip_board: ^1.0.0
  image_downloader_web: ^2.0.6
  timeago: ^3.6.1
  collection: ^1.18.0
  flutter_picker_plus: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anim/
    - assets/audio/
    - assets/google_fonts/montserrat/
    - assets/google_fonts/abril_fatface/
    - assets/google_fonts/mohave/
    - assets/google_fonts/inter/
    - assets/google_fonts/noto_sans/
    - assets/google_fonts/archivo_narrow/
    - assets/google_fonts/abeezee/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
